#!/usr/bin/env bash
#A bash script that does netweoking stuff
cp /etc/hosts ~/hosts.tmp
sed -i "s/^127\.0\.0\.1/127.0.0.2/" ~/hosts.tmp
echo "8.8.8.8		facebook.com" >> ~/hosts.tmp
cp -f ~/hosts.tmp /etc/hosts
